### ISSUE TITLE
爱奇艺弹幕解析错误

### ISSUE THREAD

**Issue by Mr-Spade** [lyz05/danmaku#8]
感谢您开发的使用工具！

在今天使用您的网站的过程中，发现爱奇艺的弹幕解析无法进行，例如，网站给出的例子：https://fc.lyz05.cn/?url=https://www.iqiyi.com/v_19rr1lm35o.html ，现在无法进行解析，会报错为：

```
弹幕解析过程中程序报错退出，请等待管理员修复！或者换条链接试试！
```

如果您能拨冗查看这个错误，将不胜感激。再次感谢！

**Comment by lyz05** [comment]
爱奇艺的问题已经解决，爱奇艺的前端页面做了些修改，详见[commit b790d75](https://github.com/lyz05/danmaku/commit/b790d75a0bc34bed248b2c3bfaf42717952fa954)
